# Generated by gallery/generate.py; do not edit.
fill -90 99 -90 -61 106 16 minecraft:air
fill -60 99 -90 -31 106 16 minecraft:air
fill -30 99 -90 -1 106 16 minecraft:air
fill 0 99 -90 29 106 16 minecraft:air
fill 30 99 -90 59 106 16 minecraft:air
fill 60 99 -90 89 106 16 minecraft:air
